# Generated by Django 3.1 on 2020-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Telefono',
            field=models.CharField(max_length=30),
        ),
    ]
